name: Solar System Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

env:
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_CLOUD: ${{vars.MONGO_CLOUD}}
  DB_NAME: ${{vars.DB_NAME}}

jobs:
  solar_system_cicd:
    name: Unit Testing
    strategy:
      matrix:
        node_version: [18, 19, 20]
        os: [ubuntu-latest, macos-latest]
        exclude:
        - node_version: 18
          os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SetUp NodeJs Version ${{ matrix.node_version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Installing Project Dependencies
        run: npm install

      - name: Unit Testing
        run: npm test

# In upload-artifact v3; it is possible to upload same artifact with matrix
# But In v4; It isn't possible as it will failed the workflow because of same artifact exist already. 
# So either use v3; or file name should be dynamic. 
      - name: Archiving Test Files
        uses: actions/upload-artifact@v3
        with:
          name: Mocha-Test-Result
          path: test-results.xml
